main_app/urls.py
from django.urls import path
from . import views
from django.contrib.auth.views import LoginView, LogoutView


urlpatterns = [  
        path('', views.home),  
        path('about/', views.about, name="about"), # path('about/', views.about, name ="about"),
        path('plants/', views.plants_index, name='plants_index'),
        path('plants/<int:plant_id>/', views.plants_detail, name='plants_detail'),
        path('plants/create/', views.PlantCreate.as_view(), name='plants_create'),
        path('plants/<int:pk>/update/', views.PlantUpdate.as_view(), name='plants_update'),
        path('plants/<int:pk>/delete/', views.PlantDelete.as_view(), name='plants_delete'),
        path('pollinators/', views.PollinatorList.as_view(), name='pollinators_index'),
        path('pollinators/<int:pk>/', views.PollinatorDetail.as_view(), name='pollinators_detail'),
        path('pollinators/create/', views.PollinatorCreate.as_view(), name='pollinators_create'),
        path('pollinators/<int:pk>/update/', views.PollinatorUpdate.as_view(), name='pollinators_update'),
        path('pollinators/<int:pk>/delete/', views.PollinatorDelete.as_view(), name='pollinators_delete'),
        path('plants/<int:plant_id>/add_watering/', views.add_watering, name='add_watering'),
        path('plants/<int:plant_id>/assoc_pollinator/<int:pollinator_id>/', views.assoc_pollinator, name='assoc_pollinator'),
        path('plants/<int:plant_id>/unassoc_pollinator/<int:pollinator_id>/', views.unassoc_pollinator, name='unassoc_pollinator'),
        path('accounts/signup/', views.signup, name='signup'),
        path('plants/<int:plant_id>/add_photo/', views.add_photo, name='add_photo'),
        # redirect to home page after login
        path('accounts/login/', LoginView.as_view(template_name='registration/login.html', next_page='/'), name='login'),
        # redirect to home page after logout
        path('accounts/logout/', LogoutView.as_view(next_page='/'), name='logout'),

    ]

plantcollector/urls.py
from django.contrib import admin
from django.urls import path, include
# from pip import debug_toolbar
import debug_toolbar


urlpatterns = [
    path('admin/', admin.site.urls),
    path('__debug__/', include(debug_toolbar.urls)),
    path('', include('main_app.urls')),
]

main_app/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User



# Create your models here.
class Pollinator(models.Model):
    name = models.CharField(max_length=100)
    description = models.TextField(max_length=250)
    lifespan = models.IntegerField()

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('pollinators_detail', kwargs={'pk': self.id})


class Plant(models.Model):
    name = models.CharField(max_length=100)
    description = models.TextField(max_length=250)
    lifespan = models.IntegerField()
    user = models.ForeignKey(User, on_delete=models.CASCADE, default=1)
    pollinators = models.ManyToManyField(Pollinator)
    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('plants_detail', kwargs={'plant_id': self.id})


    
class Watering(models.Model):
    HYDRATIONS = (
        ('M', 'Morning'),
        ('N', 'Noon'),
        ('E', 'Evening'),
    )

    date = models.DateField('Watering Date')
    hydration = models.CharField(
        max_length=1,
        choices=HYDRATIONS,
        default=HYDRATIONS[0][0]
    )
    amount = models.IntegerField(default=100)

    plant = models.ForeignKey(Plant, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.get_hydration_display()} on {self.date}"

    class Meta:
        ordering = ('-date',)

class Photo(models.Model):
   url = models.CharField(max_length=200)
   plant = models.ForeignKey(Plant, on_delete=models.CASCADE)

   def __str__(self):
      return f"Photo for plant_id: {self.plant.id} @{self.url}"

main_app/forms.py
from django.forms import ModelForm 
from .models import Watering

# create a feeding form

class WateringForm(ModelForm):
    # Meta class is a nested class that tells Django which model to base the form off of
    # and which fields to include in the form, and any special options we want to include
    # Meta class is useful because it allows us to keep our form code separate from our model code
    class Meta:
        model = Watering
        fields = ('date', 'hydration', 'amount') 

main_app/views.py
from django.shortcuts import render, redirect

from django.views.generic.edit import CreateView, DeleteView, UpdateView
from django.views.generic import ListView, DetailView
from .models import Plant, Pollinator, Watering, Photo
from .forms import WateringForm
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin

import uuid
import boto3

S3_BASE_URL = 'https://s3-us-east-2.amazonaws.com/'
BUCKET = 'plantcollector-nov8'


# Create your views here.
def home(request):
    return render(request, 'home.html')

def about(request):
    return render(request, 'about.html')

@login_required
def plants_index(request):
    return render(request, 'plants/index.html', {'plants': Plant.objects.all()})

@login_required
def plants_detail(request, plant_id):
    plant = Plant.objects.get(id=plant_id)
    watering_form = WateringForm()
    # create a list of pollinators that belong to the plant
    plant_pollinators_ids = plant.pollinators.all().values_list('id')
    #  flat = True returns a list of ids instead of a list of tuples
    pollinators_plant_doesnt_have = Pollinator.objects.exclude(id__in=plant_pollinators_ids)
    return render(request, 'plants/detail.html', {
        'plant': plant,
        'watering_form': watering_form,
        'pollinators': pollinators_plant_doesnt_have
        })

@login_required
def add_watering(request, plant_id):
    # create a ModelForm instance using the data in request.POST
    # validate user input and save the data to the db
    form = WateringForm(request.POST)
    if form.is_valid():
        # don't save the form to the db until it has the plant_id assigned
        new_watering = form.save(commit=False) # commit=False means don't save to db yet
        new_watering.plant_id = plant_id # assign the plant_id to the watering
        new_watering.save() # save the watering to the db
    return redirect('plants_detail', plant_id=plant_id)

@login_required
def assoc_pollinator(request, plant_id, pollinator_id):
    # find the plant
    plant = Plant.objects.get(id=plant_id)
    # associate the pollinator with the plant
    plant.pollinators.add(pollinator_id)
    return redirect('plants_detail', plant_id=plant_id)

@login_required
def unassoc_pollinator(request, plant_id, pollinator_id):
    # find the plant
    plant = Plant.objects.get(id=plant_id)
    # unassociate the pollinator with the plant
    plant.pollinators.remove(pollinator_id)
    return redirect('plants_detail', plant_id=plant_id)

def signup(request):
    error_message = ''
    if request.method == 'POST':
        #  create a user using the UserCreationForm
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('plants_index')
        else:
            error_message = 'Invalid sign up - try again'
        
    form = UserCreationForm()
    return render(request, 'registration/signup.html', {
        'form': form,
        'error': error_message
        })

def add_photo(request, plant_id):
    # collect photo submitted by user
    photo_file = request.FILES.get('photo-file', None)

    if photo_file:
        # connect to S3
        s3 = boto3.client('s3')

        # create a unique file name
        key = uuid.uuid4().hex[:6] + photo_file.name[photo_file.name.rfind('.'):]
        # upload the file to S3
        try:
            s3.upload_fileobj(photo_file, BUCKET, key)
            url = f"{S3_BASE_URL}{BUCKET}/{key}"
            Photo.objects.create(url=url, plant_id=plant_id)
        except Exception as error:
            print('An error occurred uploading file to S3', error)
    return redirect('plants_detail', plant_id=plant_id)


       
class PlantCreate(LoginRequiredMixin, CreateView):
    model = Plant
    fields = ['name', 'description', 'lifespan']
    template_name = 'plants/plant_form.html'

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)

class PlantUpdate(LoginRequiredMixin, UpdateView):
    model= Plant
    fields = ['name', 'description', 'lifespan']
    template_name = 'plants/plant_form.html'


class PlantDelete(LoginRequiredMixin, DeleteView):
    model = Plant
    success_url = '/plants/'
    template_name = 'plants/plant_confirm_delete.html'

class PollinatorList(LoginRequiredMixin, ListView):
    model = Pollinator
    template_name = 'pollinators/pollinator_index.html'

class PollinatorDetail(LoginRequiredMixin, DetailView):
    model = Pollinator
    template_name = 'pollinators/pollinator_detail.html'

class PollinatorCreate(LoginRequiredMixin, CreateView):
    model = Pollinator
    fields = '__all__'
    template_name = 'pollinators/pollinator_form.html'

class PollinatorUpdate(LoginRequiredMixin, UpdateView):
    model = Pollinator
    fields = '__all__'
    template_name = 'pollinators/pollinator_form.html'

class PollinatorDelete(LoginRequiredMixin, DeleteView):
    model = Pollinator
    success_url = '/pollinators/'
    template_name = 'pollinators/pollinator_confirm_delete.html'

main_app/templates/plants/detail.html
{% extends 'base.html' %}

{% block title %}
<title>Plant Detail</title>
{% endblock %}

{% block content %}
    <h1>Plant Details</h1>
    <!-- NOTE: DTL (Django Template Language) is not python, although similar -->
    <div class="row">
        <div class="col s6">
            <div class="card">
                <div class="card-content">
                    <span class="card-title">{{ plant.name }}</span>
                    <p>Description: {{ plant.description }}</p>
                    {% if plant.lifespan > 0 %}
                    <p>Lifespan: {{ plant.lifespan }} years</p>
                    {% else %}
                    <p>Lifespan: Unknown</p>
                    {% endif %}
                </div>
            </div>
            <div class="card-action">
                <a href="{% url 'plants_update' plant.id %}">Update</a>
                <a href="{% url 'plants_delete' plant.id %}">Delete</a>
              </div>
              <!-- New markup above -->
               <!-- display photos -->
            {% for photo in plant.photo_set.all %}
            <img src="{{ photo.url }}" alt="{{ plant.name }}" class="responsive-img card-panel">
        
        {% empty %} 
            <div class="card-panel blue-text center-align">No photos uploaded</div>
        {% endfor %}
        <!-- upload photos -->
        <form 
        action="{% url 'add_photo' plant.id %}" 
        method="POST" 
        enctype="multipart/form-data" 
        class="card-panel">
            {% csrf_token %}
            {{ photo_form.as_p }}
            <input type="file" name="photo-file">
            <input type="submit" value="Add Photo" class="btn blue">
        </form>
          
           
        </div>
            <div class="col s6">
                <form action="{% url 'add_watering' plant.id %}" method="POST">
                    {% csrf_token %}
                    {{ watering_form.as_p }}
                    <label for="amount">Amount in mL</label>
                    <!-- <input type="number" name="amount" id="amount" min="0" max="1000" step="1" value="0"> -->
                    <input type="submit" value="Add Watering" class="btn blue">

                </form>
                <table class="striped">
                    <thead>
                        <th>Date</th>
                        <th>Time</th>
                        <th>Amount</th>
                    </thead>
                    <tbody>
                        {% for watering in plant.watering_set.all %} 
                            <tr>
                                <td>{{ watering.date }}</td>
                                <td>{{ watering.hydration }}</td>
                                <td>{{ watering.amount }} ml</td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>


        </div>
    </div>
   

<hr/>
<div class="row">
    <div class="col s6">
        <h3>{{ plant.name }}'s Pollinators</h3>
        {% if plant.pollinators.count %}
            {% for pollinator in plant.pollinators.all %}
                <div class="card">
                    <div class="card-content">
                        <span class="card-title">{{ pollinator.name.capitalize }}</span>
                        <p>Description: {{ pollinator.description }}</p>
                        
                    </div>
                    <div class="card-action">
                        <form action="{% url 'unassoc_pollinator' plant.id pollinator.id %}" method="POST">
                            <!-- security measure for all forms in python -->
                            {% csrf_token %} 
                            <input type="submit" value = "Remove" class = "btn red">
                        </form>
                    </div>
                </div>
            {% endfor %}
        {% else %}
        <!-- insert emoji  -->

        <h5>{{ plant.name }} doesn't have any pollinators yet 🥀</h5>
        {% endif %}
    </div>

    <div class="col s6">
        <h3>Available Pollinators</h3>
        {% if pollinators.count %}
            {% for pollinator in pollinators %}
                <div class="card">
                    <div class="card-content">
                        <span class="card-title">{{ pollinator.name }}</span>
                        <p>Description: {{ pollinator.description }}</p>
                    </div>
                    <div class="card-action">
                        <form action="{% url 'assoc_pollinator' plant.id pollinator.id %}" method="POST">
                            <!-- security measure for all forms in python -->
                            {% csrf_token %} 
                            <input type="submit" value = "Add" class = "btn blue">
                        </form>
                    </div>
                </div>
            {% endfor %}
        {% else %}
        <h5>No pollinators available</h5>
        {% endif %}
    </div>
</div>

<script>
    // DOM Element references
    const datePickerEl = document.getElementById('id_date');
    const methodSelectEl = document.getElementById('id_hydration');
    // materialize init for datepicker and form select
    M.Datepicker.init(datePickerEl, {
    format: 'yyyy-mm-dd',
    defaultDate: new Date(),
    setDefaultDate: true,
    autoClose: true
  });
    M.FormSelect.init(methodSelectEl);
</script>
    
    {% endblock %}
    
 

main_app/templates/plants/index.html
<html>
    <body>
        {% extends 'base.html' %}

{% block title %}
<title>Plant List</title>
{% endblock %}

{% block content %}
    <h1>Plant List</h1>
    <!-- NOTE: DTL (Django Template Language) is not python, although similar -->
    {% for plant in plants %}
    <a href="{% url 'plants_detail' plant.id %}">
    <div class="card">
        <div class="card-content">
            <span class="card-title">{{ plant.name }}</span>
           
            <p>Description: {{ plant.description }}</p>
            {% if plant.lifespan  %}
            <p>Lifespan: {{ plant.lifespan }} years</p>
            {% else %}
            <p>Lifespan: Unknown</p>
            {% endif %}
        </div>
    </div>
</a>
    {% endfor %}

{% endblock %}

    </body>
</html>

main_app/templates/plants/plant_confirm_delete.html
<html>
    <body>
{% extends 'base.html' %}

{% block title %}

<title>Are you sure you want to delete {{object.name}}?</title>

{% endblock %}

{% block content %}
<h1>Are you sure you want to delete {{object.name}}?</h1>

<form method ="POST">
    {% csrf_token %}
    <input type="submit" value="Yes, delete {{object.name}}!" class="btn red">
    <a href="{% url 'plants_detail' object.id %}" class="btn blue">No, keep it!</a>
</form>
{% endblock %}

    </body>
</html>

main_app/templates/plants/plant_form.html
<html>
    <body>
        
        {% extends 'base.html' %}

        {% block title %}
            {% if object %}
                <title>Update {{object.name}}</title>
            {% else %}
                <title>Add a Plant</title>
            {% endif %}
        {% endblock %}
        
        {% block content %}
        <!-- New if/else block -->
        {% if object %}
            <h1>Edit <span class="teal-text">{{object.name}}</span></h1>
        {% else %}
            <h1>Add Plant</h1>
        {% endif %}
        
        <form action="" method="POST">
            {% csrf_token %}
            <table>
                {{form.as_table}}
            </table>
        
            <input type="submit" value="Submit" class="btn red">
        </form>
        {% endblock %}
    </body>
</html>